# Generated by Django 6.0 on 2026-01-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='experience',
            field=models.PositiveIntegerField(default=0, help_text='Experience in years'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='qualification',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.TextField(default='', help_text='Resume text or resume URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='skills',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
