# Generated by Django 6.0 on 2025-12-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('jobseeker', 'Job Seeker'), ('employer', 'Employer')], max_length=20),
        ),
    ]
